format = """
$character\
$os\
$username\
[](#aa3f2b)\
$directory\
[](fg:#aa3f2b bg:#6a8b52)\
$git_branch\
$git_status\
[](fg:#6a8b52 bg:#d498a3)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$python\
[](fg:#d498a3 )\
$docker_context\
$time\
[🌸 ](fg:#d498a3)\
"""

[character]
format = "$symbol "
success_symbol = "[🍙](#ba9132)"
error_symbol = "[🐼](#7e261f)"
vimcmd_symbol = "[■](#3f6b4b)"

[username]
show_always = true
style_user = "bold fg:#223847 bg:none"
format = "[$user ]($style)"

[os]
style = "bg:#fdf6e3"
disabled = true

[directory]
style = "fg:#fdf6e3 bg:#aa3f2b"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[python]
symbol = " "
style = "fg:#f3ead8 bg:#d498a3"
format = '[ $symbol($version) ]($style)'

[c]
symbol = " "
style = "fg:#f3ead8 bg:#d498a3"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "fg:#f3ead8 bg:#d498a3"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "fg:#f3ead8 bg:#2f6fa5"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "fg:#f3ead8 bg:#d498a3"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "fg:#f3ead8 bg:#d498a3"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "fg:#f3ead8 bg:#6a8b52"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#f3ead8 bg:#6a8b52"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "fg:#f3ead8 bg:#d498a3"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "fg:#f3ead8 bg:#d498a3"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "fg:#f3ead8 bg:#d498a3"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "fg:#f3ead8 bg:#d498a3"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "fg:#f3ead8 bg:#d498a3"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "fg:#f3ead8 bg:#d498a3"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "fg:#f3ead8 bg:#d498a3"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "fg:#f3ead8 bg:#d498a3"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "fg:#f3ead8 bg:#d498a3"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "fg:#d498a3"
format = '[ $time ]($style)'

[container]
disabled = true
