format = """
$character\
$os\
$username\
[](#012b38)\
$directory\
[](fg:#012b38 bg:#063642)\
$git_branch\
$git_status\
[](fg:#063642 bg:#114754)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$python\
[](fg:#114754 )\
$docker_context\
$time\
[✿ ](fg:#fdce3c)\
"""

[character]
format = "$symbol "
success_symbol = "[🐒](#d0140e)"
error_symbol = "[○](italic purple)"
vimcmd_symbol = "[■](italic dimmed green)"

[username]
show_always = true
format = "[$user ]($style)"

[os]
style = "bg:#001d24"
disabled = true

[directory]
style = "fg:#e5e5e5 bg:#012b38"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[python]
symbol = " "
style = "bg:#114754"
format = '[ $symbol($version) ]($style)'

[c]
symbol = " "
style = "bg:#114754"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "bg:#114754"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#114754"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#114754"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#063642"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#063642"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#114754"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#114754"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#114754"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#114754"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#114754"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#114754"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#114754"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#114754"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#114754"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"
format = '[ $time ]($style)'

[container]
disabled = true
