# vim: ft=tmux

##### Modes / messages
set -g mode-style "fg=#33414c,bg=#d2bc86"

set -g message-style "fg=#33414c,bg=#d2bc86"
set -g message-command-style "fg=#33414c,bg=#d2bc86"

##### Pane borders
set -g pane-border-style "fg=#d2bc86"
set -g pane-active-border-style "fg=#6a8b52"

##### Status bar base
set -g status "on"
set -g status-interval 1
set -g status-justify "left"

set -g status-style "fg=#33414c,bg=#f3ead8"
set -g status-bg "#f3ead8"

set -g status-left-length "100"
set -g status-right-length "100"

set -g status-left-style NONE
set -g status-right-style NONE

set -g status-left "#[fg=#f3ead8,bg=#aa3f2b,nobold] #S:#I.#P \
#[fg=#aa3f2b,bg=#55646f,nobold,nounderscore,noitalics]\
#[fg=#f3ead8,bg=#55646f,bold] 🐼 #(whoami) \
#[fg=#55646f,bg=#f3ead8]"

set -g status-right "#[fg=#d498a3,bg=#f3ead8,nobold,nounderscore,noitalics]\
#[fg=#f3ead8,bg=#d498a3]\
#[fg=#6a8b52,bg=#d498a3,nobold,nounderscore,noitalics]\
#[fg=#f3ead8,bg=#6a8b52]\
#[fg=#aa3f2b,bg=#6a8b52,nobold,nounderscore,noitalics]\
#[fg=#f3ead8,bg=#aa3f2b,nobold] #h "

##### WINDOW LIST

setw -g window-status-activity-style "underscore,fg=#5f6c77,bg=#f3ead8"
setw -g window-status-separator ""

setw -g window-status-style "NONE,fg=#55646f,bg=#f3ead8"
setw -g window-status-format \
'#[fg=#f3ead8,bg=#f3ead8]#[fg=#55646f] #I · #{b:pane_current_path} #[fg=#f3ead8,bg=#f3ead8,nobold,nounderscore,noitalics]'

setw -g window-status-current-format \
'#[fg=#f3ead8,bg=#aa3f2b]#[fg=#f3ead8,bg=#aa3f2b,bold] #I #[fg=#aa3f2b,bg=#6a8b52] #[fg=#f3ead8]#{b:pane_current_path} #[fg=#6a8b52,bg=#f3ead8,nobold]'
